CREATE USER BooKeeperDbUser FOR LOGIN BooKeeperDbUser;
ALTER ROLE db_datareader ADD MEMBER BooKeeperDbUser;
ALTER ROLE db_datawriter ADD MEMBER BooKeeperDbUser;
GRANT UNMASK TO BooKeeperDbUser;

CREATE TABLE [dbo].[BankAccount](
	[Id] [UNIQUEIDENTIFIER] NOT NULL,
	[Name] [NVARCHAR](100) NOT NULL
 CONSTRAINT [PK_BankAccount] PRIMARY KEY CLUSTERED
 (
	[Id] ASC
 )
 WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
